language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install .
  - pip install requests
  - pip install responses
  - pip install coveralls
  - pip install coverage
  - pip install unittest

script:
  - coverage run --source=lapostesdk test.py

after_success:
  - coveralls
